### ISSUE TITLE
Invalid resolution

### ISSUE THREAD

**Issue by Monirzadeh** [stafazzoli/FarsiOCR#15]
every time i try to use this project get bellow error
```
pytesseract.pytesseract.TesseractError: (1, 'UZN file /tmp/tess_6qnz_i5o loaded. Estimating resolution as 240 UZN file /tmp/tess_6qnz_i5o loaded. Warning. Invalid resolution 0 dpi. Using 70
instead. Too few characters. Skipping this page Error during processing.')
```

**Comment by stafazzoli** [comment]
You should check out tesseract issues regarding your error. You may find the issues below helpful:

https://github.com/https://github.com/tesseract-ocr/tesseract/issues/1702
https://github.com/ropensci/tesseract/issues/15
