### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by nisamo** [stafazzoli/FarsiOCR#3]
Hello, I tried for install and no error but when run command for convert OCR tell me error

```
C:\FarsiOCR\src>ocr.py
sample_farsi.jpeg
angle: 0
Traceback (most recent call last):
  File "C:\FarsiOCR\src\ocr.py", line 66, in <module>
    main()
  File "C:\FarsiOCR\src\ocr.py", line 47, in main
    print(text, file=text_file)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-4: character maps to <undefined>
```

**Comment by stafazzoli** [comment]
Hi,

I do not maintain this project anymore. But I ran the code and it got
executed with no error.

The error log shows that you use 'sample_farsi.jpeg'. Is this the same
sample file provided in the repository?

Try changing lines 46-47 that throws the error:

with open(outfile, 'w') as text_file:
    print(text, file=text_file)

as below:

with open(outfile, 'w', encoding='utf-8') as text_file:
    text_file.write(text)


and see if it works.

Regards,
Sajedeh

**Comment by stafazzoli** [comment]
Hi,

I ran the code and it got executed with no error. The error log shows that you use 'sample_farsi.jpeg'. Is this the same sample file provided in the repository?

Try changing lines 46-47 that throws the error:

```python
with open(outfile, 'w') as text_file:
    print(text, file=text_file)
```

as below:
```python
with open(outfile, 'w', encoding='utf-8') as text_file:
    text_file.write(text)
```
and see if it works.

**Comment by nisamo** [comment]
Hi, Working but for multi file how merge all files in doc file . also Another problem is right to left

**Comment by stafazzoli** [comment]
You can paste multiple files in the `data` folder. The application converts all the images to a separate txt file.

The .txt file does not have an alignment setting.

**Comment by stafazzoli** [comment]
I close this issue, since the reported issue is fixed now.

**Comment by stafazzoli** [comment]
I close this issue now, since the reported issue is fixed.
