### ISSUE TITLE
PDF import

### ISSUE THREAD

**Issue by nisamo** [stafazzoli/FarsiOCR#5]
Hello.

Thanks for your software

when import pdf file for import tell me this error

```
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\pdf2image\pdf2image.py", line 424, in pdfinfo_from_path
    raise PDFInfoNotInstalledError(
pdf2image.exceptions.PDFInfoNotInstalledError: Unable to get page count. Is poppler installed and in PATH?
```

Can help me?

**Comment by stafazzoli** [comment]
Hi,

You should download the [poppler file for windows](https://blog.alivate.com.au/poppler-windows/) and install it. After installation, make sure it is added to the PATH.

**Comment by nisamo** [comment]
yes working. but another problem is multi page in output. i hope fix it

when import pdf file with a lot of page output is every page in one text file. Please edit code for all pages in output also in one file

**Comment by stafazzoli** [comment]
If you want, you can append the text in each iteration to the txt file created before.
```
    with open(os.path.join(output_dir, 'output.txt'), 'a', encoding='utf-8') as text_file:
        text_file.write(text + '\n')
```

I do not intend to make this change to the code.
